datos constantes = {
    Fecha actual: "2023-01-01",
    eventos: [
      {
        _id: "639c723b992482e5f2834be9",
        Nombre: "Partido de las Colectividades",
        imagen: "https://i.postimg.cc/Fs03hQDt/Fiesta-de-las-colectividades.jpg",
        fecha: "2022-12-12",
        descripción:
          “Disfruta de tus platos favoritos, de diferentes países, en un evento único para toda la familia.”,
        Categoría: "Feria de Alimentos",
        Lugar: "Sala A",
        capacidad: 45000,
        asistencia: 42756,
        precio: 5,
        __v: 0,
      },
      {
        _id: "639c723b992482e5f2834beb",
        nombre: "estilo coreano",
        imagen: "https://i.postimg.cc/ZmD3Xf57/Estilo-coreano.jpg",
        fecha: "2023-08-12",
        descripción:
          "Disfruta de los mejores platos coreanos, con chefs internacionales y eventos increíbles".
        Categoría: "Feria de Alimentos",
        Lugar: "Sala A",
        capacidad: 45000,
        Precio: 10,
        __v: 0,
        Estimación: 42756,
      },
      {
        _id: "639c723c992482e5f2834bed",
        nombre: "Parque Jurásico",
        imagen: "https://i.postimg.cc/GmHRkbNV/Jurassic-Park.jpg",
        fecha: "2022-11-02",
        descripción:
          "Vamos a conocer los dinosaurios más grandes en el museo de paleontología".
        Categoría: "Museo",
        lugar: "Campo",
        capacidad: 82000,
        Precio: 15,
        __v: 0,
        asistencia: 65892,
      },
      {
        _id: "639c723c992482e5f2834bef",
        nombre: "Museo Parisino",
        imagen: "https://i.postimg.cc/c4C2zXm8/Museo-Parisino.jpg",
        fecha: "2023-11-02",
        descripción:
          “Un recorrido único en la ciudad de las luces, conoce uno de los lugares más icónicos.”,
        Categoría: "Museo",
        lugar: "París",
        capacidad: 8200,
        Estimación: 8200,
        Precio: 3500,
        __v: 0,
      },
      {
        _id: "639c723c992482e5f2834bf1",
        nombre: "Comicon",
        imagen: "https://i.postimg.cc/KYD0jMf2/comicon.jpg",
        fecha: "2022-02-12",
        descripción:
          "Para los amantes del cómic, todos tus personajes favoritos reunidos en un solo lugar.",
        Categoría: "Fiesta de disfraces",
        Lugar: "Sala C",
        Capacidad: 120000,
        asistencia: 110000,
        Precio: 54,
        __v: 0,
      },
      {
        _id: "639c723c992482e5f2834bf3",
        nombre: "Noche de Halloween",
        imagen: "https://i.postimg.cc/RZ9fH4Pr/halloween.jpg",
        fecha: "2023-02-12",
        Descripción: "Ven con tu disfraz más terrorífico y gana increíbles premios.",
        Categoría: "Fiesta de disfraces",
        Lugar: "Sala C",
        capacidad: 12000,
        Estimación: 9000,
        precio: 12,
        __v: 0,
      },
      {
        _id: "639c723c992482e5f2834bf5",
        nombre: "Metallica en concierto",
        imagen: "https://i.postimg.cc/PrMJ0ZMc/Metallica-en-concierto.jpg",
        fecha: "2023-01-22",
        Descripción: "El único concierto de la banda más emblemática del mundo.",
        Categoría: "Concierto de música",
        Lugar: "Sala A",
        capacidad: 138000,
        Estimación: 138000,
        Precio: 150,
        __v: 0,
      },
      {
        _id: "639c723c992482e5f2834bf7",
        nombre: "Festival Electronico",
        imagen: "https://i.postimg.cc/KvsSK8cj/Electronic-Fest.jpg",
        fecha: "2022-01-22",
        descripción:
          “Los mejores DJ’s nacionales e internacionales reunidos en un solo lugar.”,
        Categoría: "Concierto de música",
        Lugar: "Sala A",
        capacidad: 138000,
        asistencia: 110300,
        Precio: 250,
        __v: 0,
      },
      {
        _id: "639c723d992482e5f2834bf9",
        nombre: "10K de por vida",
        imagen: "https://i.postimg.cc/fyLqZY9K/10-K-por-la-vida.jpg",
        fecha: "2022-03-01",
        Descripción: "Ven a ejercitarte, mejora tu salud y estilo de vida.",
        Categoría: "Carrera",
        Lugar: "Campo de fútbol",
        capacidad: 30000,
        asistencia: 25698,
        precio: 3,
        __v: 0,
      },
      {
        _id: "639c723d992482e5f2834bfb",
        nombre: "15K NY",
        imagen: "https://i.postimg.cc/zv67r65z/15kny.jpg",
        fecha: "2023-03-01",
        descripción:
          "Recaudaremos fondos para hospitales y atención médica en este evento único que se llevará a cabo en la Gran Manzana".
        Categoría: "Carrera",
        lugar: "Nueva York",
        capacidad: 3000000,
        precio: 3,
        __v: 0,
        Estimación: 2569800,
      },
      {
        _id: "639c723d992482e5f2834bfd",
        nombre: "Feria del libro escolar",
        imagen: "https://i.postimg.cc/Sst763n6/book1.jpg",
        fecha: "2023-10-15",
        Descripción: "Trae tu libro escolar sin usar y llévate el que necesites.",
        Categoría: "Intercambio de libros",
        Lugar: "Sala D1",
        capacidad: 150000,
        Estimación: 123286,
        precio: 1,
        __v: 0,
      },
      {
        _id: "639c723d992482e5f2834bff",
        Nombre: "Solo para tu cocina",
        imagen: "https://i.postimg.cc/05FhxHVK/book4.jpg",
        fecha: "2022-11-09",
        descripción:
          "Si eres amante de la gastronomía ven a hacerte con el recetario que más se adapta a tu gusto y al de tu familia.",
        Categoría: "Intercambio de libros",
        Lugar: "Sala D6",
        capacidad: 130000,
        asistencia: 90000,
        Precio: 100,
        __v: 0,
      },
      {
        _id: "639c723d992482e5f2834c01",
        nombre: "Batman",
        imagen: "https://i.postimg.cc/vH52y81C/cinema4.jpg",
        fecha: "2022-3-11",
        Descripción: "Ven a ver a Batman luchar contra el crimen en Ciudad Gótica".
        Categoría: "Cine",
        Lugar: "Sala D1",
        capacidad: 11000,
        asistencia: 9300,
        Precio: 225,
        __v: 0,
      },
      {
        _id: "639c723d992482e5f2834c03",
        nombre: "Vengadores",
        imagen: "https://i.postimg.cc/T3C92KTN/scale.jpg",
        fecha: "2023-10-15",
        descripción:
          "Marvel's Avengers Premiere en 3D, el inicio de una saga épica con tus superhéroes favoritos.",
        Categoría: "Cine",
        Lugar: "Sala D1",
        capacidad: 9000,
        Estimación: 9000,
        Precio: 250,
        __v: 0,
      },
    ],
  };